### Label Encoder

In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [2]:
data =pd.read_csv("iris.csv",index_col=0)

In [3]:
#Changes does not effect the "data" dataframe
data1=data.copy()

In [4]:
data1.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [5]:
labelencoder = LabelEncoder()

In [6]:
data1.iloc[:, -1] = labelencoder.fit_transform(data1.iloc[:,-1])

In [7]:
data1.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
1           5.1          3.5           1.4          0.2        0
2           4.9          3.0           1.4          0.2        0
3           4.7          3.2           1.3          0.2        0
4           4.6          3.1           1.5          0.2        0
5           5.0          3.6           1.4          0.2        0

In [8]:
data1.tail()

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
146           6.7          3.0           5.2          2.3        2
147           6.3          2.5           5.0          1.9        2
148           6.5          3.0           5.2          2.0        2
149           6.2          3.4           5.4          2.3        2
150           5.9          3.0           5.1          1.8        2

### One Hot Encoder

#### Using sklearn

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
data2=data.copy()

In [11]:
data2=data2.reset_index().drop(['index'],axis=1)

In [12]:
# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')

In [13]:
# passing bridge-types-cat column (label encoded values of bridge_types)
enc_df = pd.DataFrame(enc.fit_transform(data2[['Species']]).toarray())

In [14]:
# merge with main df bridge_df on key values
data_final = data2.join(enc_df)
data_final

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,0,1,2
0,5.1,3.5,1.4,0.2,setosa,1.0,0.0,0.0
1,4.9,3.0,1.4,0.2,setosa,1.0,0.0,0.0
2,4.7,3.2,1.3,0.2,setosa,1.0,0.0,0.0
3,4.6,3.1,1.5,0.2,setosa,1.0,0.0,0.0
4,5.0,3.6,1.4,0.2,setosa,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,0.0,0.0,1.0
146,6.3,2.5,5.0,1.9,virginica,0.0,0.0,1.0
147,6.5,3.0,5.2,2.0,virginica,0.0,0.0,1.0
148,6.2,3.4,5.4,2.3,virginica,0.0,0.0,1.0
149,5.9,3.0,5.1,1.8,virginica,0.0,0.0,1.0

#### Using Pandas

In [15]:
import pandas as pd

In [16]:
data3=data.copy()

In [17]:
data_encoded=pd.get_dummies(data3)

In [18]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
1,5.1,3.5,1.4,0.2,1,0,0
2,4.9,3.0,1.4,0.2,1,0,0
3,4.7,3.2,1.3,0.2,1,0,0
4,4.6,3.1,1.5,0.2,1,0,0
5,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,0,0,1
147,6.3,2.5,5.0,1.9,0,0,1
148,6.5,3.0,5.2,2.0,0,0,1
149,6.2,3.4,5.4,2.3,0,0,1
150,5.9,3.0,5.1,1.8,0,0,1

#### IsolationForest

In [19]:
from sklearn.ensemble import IsolationForest

In [20]:
data =pd.read_csv("../input/eda123/iris (1).csv",index_col=0)
data_encoded=pd.get_dummies(data)

FileNotFoundError: [Errno 2] No such file or directory: '../input/eda123/iris (1).csv'

In [21]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)

IsolationForest(contamination=0.01, random_state=10)

In [22]:
# predictions
y_pred_outliers = clf.predict(data_encoded)

In [23]:
#-1 for outliers and 1 for inliers.
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [24]:
## Let us add a new data point which is outlier
data_encoded.loc[150]=[20,40,30,50,1,0,0]

In [25]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)
# predictions
y_pred_outliers = clf.predict(data_encoded)
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1])

In [26]:
data_encoded['scores']=clf.decision_function(data_encoded)

In [27]:
data_encoded['anomaly']=clf.predict(data_encoded.iloc[:,0:7])

In [28]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,scores,anomaly
1,5.1,3.5,1.4,0.2,1,0,0,0.202073,1
2,4.9,3.0,1.4,0.2,1,0,0,0.185411,1
3,4.7,3.2,1.3,0.2,1,0,0,0.174012,1
4,4.6,3.1,1.5,0.2,1,0,0,0.182873,1
5,5.0,3.6,1.4,0.2,1,0,0,0.199432,1
...,...,...,...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,0,0,1,0.164313,1
147,6.3,2.5,5.0,1.9,0,0,1,0.133436,1
148,6.5,3.0,5.2,2.0,0,0,1,0.179224,1
149,6.2,3.4,5.4,2.3,0,0,1,0.125229,1
150,20.0,40.0,30.0,50.0,1,0,0,-0.287374,-1

In [29]:
#Print the outlier data points
data_encoded[data_encoded['anomaly']==-1]

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,scores,anomaly
107,4.9,2.5,4.5,1.7,0,0,1,-0.009111,-1
150,20.0,40.0,30.0,50.0,1,0,0,-0.287374,-1

### PPS score

In [30]:
#install the package
!pip install ppscore

Collecting ppscore

WARNING: Error parsing requirements for notebook: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\notebook-6.4.8.dist-info\\METADATA'
WARNING: Error parsing requirements for nest-asyncio: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\nest_asyncio-1.5.1.dist-info\\METADATA'
WARNING: Error parsing requirements for nbformat: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\nbformat-5.1.3.dist-info\\METADATA'
WARNING: Error parsing requirements for nbconvert: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\nbconvert-6.1.0.dist-info\\METADATA'
WARNING: Error parsing requirements for nbclient: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\nbclient-0.5.11.dist-info\\METADATA'
WARNING: Error parsing requirements for mistune: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\mistune-0.8.4.dist-info\\METADATA'

  Downloading ppscore-1.2.0.tar.gz (47 kB)
     -------------------------------------- 47.1/47.1 KB 584.3 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in c:\users\user\.conda\envs\sap\lib\site-packages (from ppscore) (1.4.1)
Collecting scikit-learn<1.0.0,>=0.20.2
  Downloading scikit_learn-0.24.2-cp38-cp38-win_amd64.whl (6.9 MB)
     ---------------------------------------- 6.9/6.9 MB 2.3 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.18.5 in c:\users\user\.conda\envs\sap\lib\site-packages (from pandas<2.0.0,>=1.0.0->ppscore) (1.22.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\user\.conda\envs\sap\lib\site-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\.conda\envs\sap\lib\site-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2021.3)
Requirement already satisfied: scipy>=0.19.1 in c:\users\user\appdata\roaming\python\python38\site-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (1.4.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\user\.conda\envs\sap\lib\site-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (3.1.0)
Requirement already satisfied: joblib>=0.11 in c:\users\user\.conda\envs\sap\lib\site-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\user\.conda\envs\sap\lib\site-packages (from python-dateutil>=2.8.1->pandas<2.0.0,>=1.0.0->ppscore) (1.16.0)
Building wheels for collected packages: ppscore
  Building wheel for ppscore (setup.py): started
  Building wheel for ppscore (setup.py): finished with status 'done'
  Created wheel for ppscore: filename=ppscore-1.2.0-py2.py3-none-any.whl size=13068 sha256=77c4026ecff1e64ef1ea614e6ccfe01c58e4c3b585adf27e6a6771190cc445bf
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\fb\0e\65\da65ce669381fc01b6ef990d301d3586991f89bff1175877a4
Successfully built ppscore
Installing collected packages: scikit-learn, ppscore
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
Successfully installed ppscore-1.2.0 scikit-learn-0.24.2

WARNING: Error parsing requirements for matplotlib-inline: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\matplotlib_inline-0.1.2.dist-info\\METADATA'
WARNING: Error parsing requirements for markupsafe: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\MarkupSafe-2.0.1.dist-info\\METADATA'
WARNING: Error parsing requirements for jupyterlab-pygments: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\jupyterlab_pygments-0.1.2.dist-info\\METADATA'
WARNING: Error parsing requirements for jupyter-core: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\jupyter_core-4.9.1.dist-info\\METADATA'
WARNING: Error parsing requirements for jupyter-client: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\jupyter_client-7.1.2.dist-info\\METADATA'
WARNING: Error parsing requirements for jsonschema: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\jsonschema-3.2.0.dist-info\\METADATA'
WARNING: Error parsing requirements for jinja2: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\Jinja2-3.0.2.dist-info\\METADATA'
WARNING: Error parsing requirements for jedi: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\jedi-0.18.1.dist-info\\METADATA'
WARNING: Error parsing requirements for ipython: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\ipython-7.31.1.dist-info\\METADATA'
WARNING: Error parsing requirements for ipython-genutils: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\ipython_genutils-0.2.0.dist-info\\METADATA'
WARNING: Error parsing requirements for ipykernel: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\ipykernel-6.4.1.dist-info\\METADATA'
WARNING: Error parsing requirements for importlib-metadata: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\importlib_metadata-4.8.2.dist-info\\METADATA'
WARNING: Error parsing requirements for defusedxml: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\defusedxml-0.7.1.dist-info\\METADATA'
WARNING: Error parsing requirements for decorator: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\decorator-5.1.1.dist-info\\METADATA'
WARNING: Error parsing requirements for debugpy: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\debugpy-1.5.1.dist-info\\METADATA'
WARNING: Error parsing requirements for colorama: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\colorama-0.4.4.dist-info\\METADATA'
WARNING: Error parsing requirements for cffi: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\cffi-1.15.0.dist-info\\METADATA'
WARNING: Error parsing requirements for bleach: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\bleach-4.1.0.dist-info\\METADATA'
WARNING: Error parsing requirements for backcall: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\backcall-0.2.0.dist-info\\METADATA'
WARNING: Error parsing requirements for attrs: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\attrs-21.4.0.dist-info\\METADATA'
WARNING: Error parsing requirements for argon2-cffi: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\argon2_cffi-21.3.0.dist-info\\METADATA'
WARNING: Error parsing requirements for argon2-cffi-bindings: [Errno 2] No such file or directory: 'c:\\users\\user\\.conda\\envs\\sap\\lib\\site-packages\\argon2_cffi_bindings-21.2.0.dist-info\\METADATA'
WARNING: You are using pip version 22.0.4; however, version 22.1 is available.
You should consider upgrading via the 'C:\Users\user\.conda\envs\SAP\python.exe -m pip install --upgrade pip' command.

In [31]:
import ppscore as pps
#pps.score(df, "feature_column", "target_column")  syntax
pps.score(data, "Sepal.Length", "Petal.Length")

ModuleNotFoundError: No module named 'ppscore'

In [ ]:
#calculate the whole PPS matrix
pps.matrix(data)